Coulmn vector // Row vector

In [1]:
import numpy as np

In [2]:
a = np.array([[3,5,7]])

In [3]:
a.shape

(1, 3)

In [4]:
a = np.array([[3,5,7]]).T

In [5]:
a.shape

(3, 1)

In [6]:
a

array([[3],
       [5],
       [7]])

In [7]:
a = np.array([[3,5,7]])

In [8]:
a = a.reshape(3,1)

Vectorization - Single Instruction multiple Data SIMD

In [9]:
import time

In [10]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [11]:
c = 0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()
print("Non - Vectorized Version",str(1000*(toc - tic)),"ms")
print(c)

Non - Vectorized Version 361.8440628051758 ms
250037.222923389


Vectorized Version 

In [12]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("Vectorized Version",str(1000*(toc - tic)),"ms")
print(c)

Vectorized Version 4.952430725097656 ms
250037.22292339252


Matrix multiplication

In [13]:
a = np.random.randn(3, 2) 
b = np.random.randn(2, 1) 
c = np.dot(a,b)

In [14]:
c.shape

(3, 1)

Element-wise multiplication

In [15]:
a = np.array([[3,8],[-3,7]])
b = np.array([[1,9],[9,-6]])

In [16]:
a

array([[ 3,  8],
       [-3,  7]])

In [17]:
b

array([[ 1,  9],
       [ 9, -6]])

In [18]:
np.multiply(a,b)    #a*b

array([[  3,  72],
       [-27, -42]])

**Broadcast**

In [21]:
a

array([[ 3,  8],
       [-3,  7]])

In [20]:
a+7

array([[10, 15],
       [ 4, 14]])

In [23]:
b = np.array([2,1])

In [24]:
a*b

array([[ 6,  8],
       [-6,  7]])

In [25]:
a

array([[ 3,  8],
       [-3,  7]])

In [26]:
b = np.array([2,1]).T

In [27]:
a*b

array([[ 6,  8],
       [-6,  7]])

In [28]:
a = np.array([[3,2,5],[1,7,8],[-1,4,3]])
b = np.array(([3,8,4]))
c = a*b

In [29]:
a

array([[ 3,  2,  5],
       [ 1,  7,  8],
       [-1,  4,  3]])

In [30]:
b

array([3, 8, 4])

In [31]:
c

array([[ 9, 16, 20],
       [ 3, 56, 32],
       [-3, 32, 12]])

In [32]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [40]:
import numpy as np
a = np.array([3,5,6])
b = np.array([1,-2,4])

In [41]:
a.shape

(3,)

In [42]:
np.dot(a,b)   # matrix multiplication

17

In [43]:
a = np.array([[3,5,6],[1,2,3]])
b = np.array([1,-2,4])
#b = np.array([[1,-2,4]])

In [44]:
b.shape

(3,)

In [45]:
np.dot(a,b)   # matrix multiplication but repeat 

array([17,  9])

In [ ]:
a1 = np.array([1,4,5])
a2 = np.array([2,4,5])
a1*a2    #inner product

In [ ]:
a1 = np.array([[1,4,5],[2,-2,0]])
a2 = np.array([2,4,5])
a1*a2    #inner product